
[typescript-language-server]
requirement =
    typescript
    typescript-language-server

[bash-language-server]

[readable]
requirement =
    readability-cli
    # force upgrade to be >0.4.4...
    @mozilla/readability

#[readable6]
#requirement =
#    readability-cli
#    @mozilla/readability
#target = readable

# re-enable if using svelte with LSP editors...
#[svelteserver]
#requirement =
#    svelte-language-server
