#!/bin/sh
# elvis: dockerhub       -- Search the Docker Hub for container images
. surfraw || exit 1

w3_config
w3_parse_args "$@"
# now in $w3_args

escaped=$(w3_url_of_arg "$w3_args")
w3_browse_url "https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=${escaped}&starCount=0"
