#!/bin/sh
# elvis: pypi            -- Search the Python Package Index (Cheeseshop)
. surfraw || exit 1

w3_config
w3_parse_args "$@"
# now in $w3_args

escaped=$(w3_url_of_arg "$w3_args")
w3_browse_url "https://pypi.python.org/pypi?%3Aaction=search&term=${escaped}&submit=search"
