#!/bin/sh
# elvis: timeanddate     -- Search timezones around the world
. surfraw || exit 1

w3_config
w3_parse_args "$@"
# now in $w3_args

escaped=$(w3_url_of_arg "$w3_args")
w3_browse_url "https://www.timeanddate.com/worldclock/?query=${escaped}"
